FROM php:7.0-fpm

WORKDIR /usr/src

#install composer
RUN apt-get update
RUN apt-get install -y curl php5-cli git
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /usr/share/nginx/html

#install package
CMD ["composer", "update"]